version: '3.1'

services:
  app-frontend:
    build:
      context: .
      dockerfile: "../../../Dockerfile"
    ports:
      - "4210:4200"
    networks:
      - app-liquidation
    environment:
      - apiUrl=http://app-back:8087


networks:
  app-liquidation:
    driver: bridge
